version: '3.7'

volumes:
  dbs:

services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: .
    env_file:
      - .env
    volumes:
      - type: volume
        source: dbs
        target: /app/dbs
    restart: on-failure
